### ISSUE TITLE
Some labels are not shown for lots of data

### ISSUE THREAD

**Issue by enricocolasante** [benkeen/d3pie#65]
![d3pie](https://cloud.githubusercontent.com/assets/4367852/6781081/7577aa1c-d149-11e4-8107-d749db04eb8f.png)

At the bottom of the chart the labels are not shown, they seem to be out of the chart.

**Comment by benkeen** [comment]
Thanks for the bug report, @enricocolasante.

**Comment by WACMemphis** [comment]
I've got the same issue. Even when I use `hideWhenLessThanPercentage: 1`. Looking forward to a solution.

**Comment by obfuscoder** [comment]
The function resolveOuterLabelCollisions is responsible. It "corrects" the label positions to prevent overlappings. The calculation is done even if the conflicting labels are not shown based on the percentage boundary. Only the opacity of the labels is set to zero when creating theSVG elements. They are still rendered at their calculated positions.

It would help to use the percentage boundary check in resolveOuterLabelCollisions to skip collision checks for labels which will not be shown.

It would also make more sense, to correct the positions of the labels in the clockwise direction instead of ccw and automatically hide the label and line as soon as it gets out of the upper frame bounds. This way only the smallest amounts are hidden.

**Comment by obfuscoder** [comment]
I created a PR for fixing this issue.

It does not entirely fix letting collisions get out of rendering frames, but when using the option **hideWhenLessThanPercentage** on outer labels, the collision detection takes the actual rendering of the labels into account.

```
"labels": {
          "outer": {
            "hideWhenLessThanPercentage": 2
          },
```

**Comment by benkeen** [comment]
Thanks for the PR, @obfuscoder! Merged. This will be in 0.2.0 - just working through the backlog of issues, but I hope to get it out soon.

**Comment by sebastian-raubach** [comment]
@benkeen Any update as to when we can expect version 0.2.0?
